# Project information
site_name: Multi-tenancy Assets for IBM Clients  to build SaaS
site_url: https://ibm.github.io/multi-tenancy-documentation
site_author: Niklas Heidloff, Adam de Leeuw, Alain Airom, Thomas Suedbroecker

# Repository
repo_name: Multi-tenancy Assets for IBM Clients  to build SaaS
repo_url: https://github.com/ibm/multi-tenancy
edit_uri: edit/main/documentation
docs_dir: documentation

# Navigation
nav:
  - Introduction: ./placeholder.md  
  - Development of Microservices:
    - Quarkus Backend Service Code: ./development_of_microservices/backend-service-impl.md
    - Quarkus Backend Service Container: ./development_of_microservices/backend-service-container.md
    - Vue.js Frontend Service Code: ./development_of_microservices/frontend-service-code.md
    - Vue.js Frontend Service Container: ./development_of_microservices/frontend-service-container.md
    - Externalization of Variables in Backend Microservices: ./development_of_microservices/externalization-of-variables-in-backend-microservices.md
    - Externalization of Variables in Frontend Microservices: ./development_of_microservices/externalization-of-variables-in-frontend-microservices.md
    - Local Development of Services: ./development_of_microservices/local-development.md
    - Authentication Flow (AppID, backend, frontend): ./development_of_microservices/authentication-flow-appip-backend-frontend.md
  - Creation of managed IBM Cloud Services:
    - Database:
      - Programmatic Creation of Postgres: ./creation-of-managed-ibm-cloud-services/create-postgres.md
      - Programmatic Configuration of Postgres including Schema: ./creation-of-managed-ibm-cloud-services/create-postgres-schema.md
    - Authentication:
      - Programmatic Creation of AppID: ./creation-of-managed-ibm-cloud-services/create-appid.md
      - Programmatic Configuration of AppID: ./creation-of-managed-ibm-cloud-services/configure-appid.md
  - Serverless via IBM Code Engine:
    - Architecture: ./placeholder.md
    - Initial Setup via Scripts: 
      - a. Create the instances: ./serverless-via-ibm-code-engine/ce-setup-create-the-instances.md
      - b. Verify the created instances: ./serverless-via-ibm-code-engine/ce-verify-the-created-instances.md
    - CI/CD: ./serverless-via-ibm-code-engine/serverless-cicd.md
    - Onboarding: ./serverless-via-ibm-code-engine/code-engine-onboarding.md
    - Observability (logging, monitoring, vulnerabilities): ./placeholder.md
    - Billing: ./placeholder.md
    - Clean Up: ./serverless-via-ibm-code-engine/ce_clean_up.md
  - Kubernetes via IBM Kubernetes Service and IBM OpenShift:
    - Architecture: ./placeholder.md
    - Initial Setup via Scripts: ./placeholder.md
    - CI/CD DevSecOps:
      - Overview: ./placeholder.md
      - CI:
        - CI pull request: ./placeholder.md
        - CI pipeline: ./placeholder.md
      - CD: 
        - CD pull request: ./placeholder.md
    - Security and Compliance: 
      - CI Toolchains: ./placeholder.md
      - CD Toolchains: ./placeholder.md
    - Onboarding: ./placeholder.md
    - Observability (logging, monitoring, vulnerabilities): ./placeholder.md
    - Billing: ./placeholder.md

## DO NOT CHANGE BELOW THIS LINE

# Copyright
copyright: Copyright &copy; 2022 IBM Developer

# Theme
theme:
  name: material
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  icon:
    # .svg automatically appended
    # logo: ibm_8bar_reverse_2
    logo: material/library
  features:
    # - navigation.tabs
    - navigation.instant
    # - navigation.expand
  palette:
    scheme: default
    primary: black
    accent: blue
  # palette:
  #  scheme: default
  #  primary: blue
  #  accent: blue
  # enable if you want to use a custom icon
  # custom_dir: overrides

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ibm/multi-tenancy
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ibmdeveloper
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ibm/

extra_css:
  - docs/stylesheets/extra.css
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
